#!/bin/sh

action=$CNAB_ACTION
greeting=${GREETING:-"Hi! let's install the sample Spring Music demo app on Azure"}

echo "[== $greeting Duffle user ==]"
case $action in
    install)
        echo "Run az login with service principal to access Azure sub"
        echo $client_id
        az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

        echo "Creating a resource group for AKS"
        az group create --name $AKS_RESOURCE_GROUP --location $LOCATION

        echo "Creating AKS cluster named $CLUSTER_NAME in resource group $AKS_RESOURCE_GROUP"
        az aks create -n $CLUSTER_NAME -g $AKS_RESOURCE_GROUP --node-count 3 --generate-ssh-keys --service-principal $AZURE_CLIENT_ID --client-secret $AZURE_CLIENT_SECRET

        echo "Get creds for AKS cluster"
        az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $CLUSTER_NAME

        echo "Initialize helm on cluster"
        kubectl apply -f /cnab/app/rbac-config.yaml
        helm init --service-account tiller --upgrade

        echo "Creating a resource group called $APP_RESOURCE_GROUP for the Mongo Cosmos DB service..."
        az group create --name $APP_RESOURCE_GROUP --location $LOCATION

        echo "Creating a Mongo Cosmos DB service..."
        az cosmosdb create --name $COSMOSDB_SERVICE_NAME --resource-group $APP_RESOURCE_GROUP --kind MongoDB

        echo "Get Cosmos DB connection string with credentials"
        export COSMOSDB_CONNECT_STRING=$(az cosmosdb list-connection-strings --resource-group $APP_RESOURCE_GROUP --name $COSMOSDB_SERVICE_NAME --query "connectionStrings[0].connectionString" -o tsv)
        echo $COSMOSDB_CONNECT_STRING
        
        echo "Installing application chart with connection string to Cosmos updated..."
        helm upgrade --install spring-music /cnab/app/charts/spring-music --set deploy.cosmosConnectString=$COSMOSDB_CONNECT_STRING
        
        echo "Your Spring Music demo application is installed!"

        ;;
    uninstall)
        echo "uninstall action"
        az group delete $APP_RESOURCE_GROUP
        ;;
    upgrade)
        echo "Upgrade action"
        ;;
    status)
        echo "Status action"
        ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "Action $action complete for $name"
